version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  build:
    commands:
      - sam build -s sam-app --debug
      - sam package -s sam-app --debug
artifacts:
  files:
    - template.yaml
    - samconfig_dev.toml
