version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  build:
    commands:
      - sam build -t sam-app/template.yaml --debug
      - sam package -t sam-app/template.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-x7fg0grk3glj --s3-prefix hello-world-lambda --debug --output-template-file sam-app/packaged-template.yaml
artifacts:
  files:
    - sam-app/packaged-template.yaml
    - sam-app/samconfig.toml
    - pipeline/deployspec.yml
