version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  build:
    commands:
      - sam build -t sam-app/template.yaml --debug
      - sam build -t sam-app/template.yaml --config-file sam-app/samconfig.toml --debug
artifacts:
  files:
    - sam-app/template.yaml
    - sam-app/samconfig.toml
    - pipeline/deployspec.yml
